export const EDIT_PRODUCT = 'EDIT_PRODUCT'
// Look at redux-forms so only top level on change required
export const EDIT_PRODUCT_TYPE_CHANGED = 'EDIT_PRODUCT_TYPE_CHANGED'
export const EDIT_PRODUCT_DESCRIPTION_CHANGED = 'EDIT_PRODUCT_DESCRIPTION_CHANGED'
export const EDIT_PRODUCT_COST_CHANGED = 'EDIT_PRODUCT_COST_CHANGED'
export const SAVE_PRODUCT = 'SAVE_PRODUCT'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
